### ISSUE TITLE
Homepage metatitle with "undefined

### ISSUE THREAD

**Issue by WengerK** [webmardi/webmardi.ch#108]
It seems the last change on #103 leads to a bug on Homepage where we now got "undefined"

![image](https://github.com/webmardi/webmardi.ch/assets/1841592/a1aff27b-1096-4388-a684-bd0e404b2542)

```html
<title>undefined - Webmardi - Monthly events in western Switzerland</title>
```

<img width="699" alt="Screenshot 2024-01-29 at 15 29 48" src="https://github.com/webmardi/webmardi.ch/assets/1841592/3ad058f2-dc5e-46bc-b661-5f1a19096100">

**Comment by Yago** [comment]
Fixed with https://github.com/webmardi/webmardi.ch/releases/tag/v1.4.1

**Comment by WengerK** [comment]
Many thanks !!!
