### ISSUE TITLE
Improve the Speaker card design on canonical talk page

### ISSUE THREAD

**Issue by WengerK** [webmardi/webmardi.ch#119]
**💬 Description de la demande**

Nous aimerions savoir si il serait possible d'améliorer le design de la section "Speaker" dans un talk
https://webmardi.ch/events/148-jonathan-pernet-le-digital-applique-a-l-architecture

![CleanShot 2024-06-02 at 11 16 37@2x](https://github.com/webmardi/webmardi.ch/assets/1841592/c67b9ae6-ef2c-4c19-90ac-7457dc94c6c8)

L'idée serait d'aligner les informations après le label (si possible) et d'avoir le titre de la personne sur une deuxième ligne, alignée à son nom

🎤 Speaker - [Jonathan Pernet](https://webmardi.ch/events/148-jonathan-pernet-le-digital-applique-a-l-architecture/www.linkedin.com/in/jonathan-pernet-32a842224)
                      Associé administrateur Alegoria digital SA | CCHE
💬 Will be held in French
💻 Accessible for everyone
📍CCHE - Rue du Grand-Pré 2b · 1000 Lausanne

**Comment by Yago** [comment]
✅ Done in https://github.com/webmardi/webmardi.ch/releases/tag/v2.0.5 

Just a quick reminder : I'm still not omniscient, so if you want me to be aware of an issue, feel free to assign the issue to me or at least, ping my username in the description 😉
