### ISSUE TITLE
Remove newsletter sign up form

### ISSUE THREAD

**Issue by gperriard** [webmardi/webmardi.ch#122]
Since we will deprecate the newsletter, could you please remove the newsletter sign up form from the website?

**Comment by Yago** [comment]
✅ Done in https://github.com/webmardi/webmardi.ch/releases/tag/v2.0.5 

Just a quick reminder : I'm still not omniscient, so if you want me to be aware of an issue, feel free to assign the issue to me or at least, ping my username in the description 😉

**Comment by gperriard** [comment]
Thank you @Yago 

Next time, I'll assign it to you :)
