### ISSUE TITLE
All sponsors are displayed on the website

### ISSUE THREAD

**Issue by gperriard** [webmardi/webmardi.ch#123]
To align with the sponsoring package in 2025, we would like to display all the sponsors on the website.
There are two kind of sponsoring
- Main (limit of 6)
- Support (unlimited)

For both the logo must be clickable and should lead to the sponsor's website.
Main sponsor should be highlighted compared to the support sponsors (could be in size for instance).

The new sponsors logo should be deployed on production on the 01.01.25. Not before

**Comment by Yago** [comment]
@gperriard @WengerK Do we need a new design for this?

**Comment by WengerK** [comment]
I can ask to Pierre George help indeed

**Comment by WengerK** [comment]
Voici la proposition de Pierre

![WebMardi - 1 (1)](https://github.com/user-attachments/assets/7ac9fc46-1749-46c7-9ce7-8df11f482b76)

Le seul ajustement qu'on aimerait apport, écrire `Main sponsor` et `Supporting sponsor` dans les tags.

**Comment by Yago** [comment]
@WengerK @gperriard It's ready in a [PR](https://github.com/webmardi/webmardi.ch/pull/126) 😉

**Comment by gperriard** [comment]
Helllo @Yago 
Thank you for the work. The result look great!

Would you have capacity to adapt/add new sponsors mid December and deploy this PR on the 01.01.25?
Since we're working on sponsoring, there might be new or different sponsors. By mid December, we should be done with the sponsoring and I would be able to give you the logos and websites of all the sponsors.

Cheers,
Geoffroy

**Comment by Yago** [comment]
Certainly, @gperriard. I anticipated some modifications; I'm simply laying the groundwork. Please update me as soon as you have additional information!

**Comment by gperriard** [comment]
Thank you @Yago 

I'll update you as soon as we close the sponsoring round.

**Comment by gperriard** [comment]
Hello @Yago ,

You can find the logo of the sponsors using the link below.
[Sponsors assets.zip](https://github.com/user-attachments/files/17805589/Sponsors.assets.zip)

Logos are prefixed with "main" and "support" depending on the type of sponsoring.

Could you please add them on the website and deploy on the 31.12.2024?

Thank you,
Geoff.

**Comment by Yago** [comment]
@gperriard It's ready for the 2024.12.31 😉

![CleanShot 2024-11-24 at 17 20 15@2x](https://github.com/user-attachments/assets/13e3b6a5-b544-4db6-ac90-cf2eb3b804b0)

**Comment by Yago** [comment]
@gperriard It's ready for the 2024.12.31 😉


![CleanShot 2024-11-24 at 18 24 45@2x](https://github.com/user-attachments/assets/7deea884-6315-48db-84be-9a1457309c91)

**Comment by gperriard** [comment]
Thank you @Yago 
It looks good :)

**Comment by Yago** [comment]
It's released

**Comment by gperriard** [comment]
Thank you @Yago for the work and the release.
Happy New Year ! :)
