### ISSUE TITLE
Update sponsoring brochure

### ISSUE THREAD

**Issue by gperriard** [webmardi/webmardi.ch#129]
![Screenshot 2024-10-30 at 18 32 44](https://github.com/user-attachments/assets/b2a25b3f-b59a-4600-9fd5-9c2da245178d)

Could you please update the sponsoring package document with the new one for 2025?
It's available here: https://drive.google.com/file/d/1M64QtHC7TClYMAYKwm4momwVmYO5yVvn/view?usp=drive_link

Thanks for your help :)

**Comment by gperriard** [comment]
Hello @Yago ,

Could you help me update the sponsor brochure on the website with the one below?
[Webmardi - Sponsoring _ partnering 2025.pdf](https://github.com/user-attachments/files/17874498/Webmardi.-.Sponsoring._.partnering.2025.pdf)

Regards,
Geoffroy

**Comment by Yago** [comment]
@gperriard Sure, I just release the [2.0.8](https://github.com/webmardi/webmardi.ch/releases/tag/v2.0.8) with the new PDF 😉

**Comment by gperriard** [comment]
Great !
Thank you very much @Yago
