### ISSUE TITLE
Add the talk language

### ISSUE THREAD

**Issue by Greaby** [webmardi/webmardi.ch#54]
Can we add a new column in Notion that will allow us to display the language of the talk?
How about displaying it right after the category?

**Comment by Yago** [comment]
Sure! It's a good idea. But could it make more sense to display it alongside the time and the location like so?

![CleanShot 2022-01-19 at 08 43 33](https://user-images.githubusercontent.com/2025924/150086353-9ae32bc3-a3a7-4428-835c-dc6a8277a577.png)

**Comment by Greaby** [comment]
Yes you are right! It makes more sense to put it here.

**Comment by Yago** [comment]
Done! I just release a new version of the site with this feature. You'll need to fill the new column and re-deploy the site to see any effects 😉

![CleanShot 2022-01-21 at 16 21 39](https://user-images.githubusercontent.com/2025924/150555708-844ea66b-994f-4e4b-b611-2eeef6b28270.png)

**Comment by Greaby** [comment]
Thanks ! :)
