### ISSUE TITLE
Google Analytics 4

### ISSUE THREAD

**Issue by WengerK** [webmardi/webmardi.ch#64]
**💬 Description de la demande**

Hello @Yago,

Google va drop Google Analytics 3 très très très bientôt et nous voudrions savoir si tu pouvais déjà mettre en place le nouveau code GA4 que voici

for now, dont replace the old Google Analytics just add this new script

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-4PZVCNZ6D5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-4PZVCNZ6D5');
</script>
``` 

**🔢 Tâches**

- Ajouter le code GA4
- Garder l'ancien analytics le temps de voir si tout est OK

**Comment by Yago** [comment]
Oui, pas de soucis, je fait ça asap 😉

**Comment by WengerK** [comment]
it works many thanks !
