### ISSUE TITLE
When the Job title contains a dot it does not render

### ISSUE THREAD

**Issue by WengerK** [webmardi/webmardi.ch#75]
See Labster.io for Adeline Radius

<img width="1245" alt="Screenshot 2023-01-11 at 16 53 58" src="https://user-images.githubusercontent.com/1841592/211853272-8f09504e-b7fe-453c-bfe6-f5cef66bd0ac.png">

<img width="273" alt="Screenshot 2023-01-11 at 16 53 44" src="https://user-images.githubusercontent.com/1841592/211853276-9393e893-3e59-4f88-ae20-4a3949ffa1a9.png">

**Comment by Yago** [comment]
Ok, I'll check that asap 👌

**Comment by Yago** [comment]
https://github.com/webmardi/webmardi.ch/releases/tag/v1.1.4

**Comment by WengerK** [comment]
<3
