### ISSUE TITLE
Move "event" to "past event" later than 19:00

### ISSUE THREAD

**Issue by Alqua** [webmardi/webmardi.ch#76]
The website as it is now moves (display them as past event) events on the same day at 19:00. Would it be possible to change that time to 23:00 (or something similar)?

When a user check the website at 19:03, the event is already in past events and that makes it harder to find.

**Comment by Yago** [comment]
I'll do it Friday 😉

**Comment by Yago** [comment]
Done and [released](https://github.com/webmardi/webmardi.ch/releases/tag/v1.1.6) !

**Comment by WengerK** [comment]
<3 <3 <3
