### ISSUE TITLE
Add livestream button to event

### ISSUE THREAD

**Issue by Alqua** [webmardi/webmardi.ch#77]
It would be nice if the event on top could include a livestream button when the link to youtube is available.

Thanks :)

**Comment by Yago** [comment]
@Alqua Normally, this should already be the case : when there is a YouTube link, [it should be displayed](https://github.com/webmardi/webmardi.ch/blob/main/src/components/EventTeaser/EventTeaser.tsx#L141) 🤔 Did you have an example in mind ?

**Comment by Alqua** [comment]
To be honest, I've never seen the link when the event is on top but perhaps it is also due to how we deal with content.
@Greaby @WengerK What do you think? Do you already have the youtube link for the next event? Could we try it?

**Comment by WengerK** [comment]
<img width="1416" alt="Screenshot 2023-01-24 at 11 59 41" src="https://user-images.githubusercontent.com/1841592/214274803-e37def3e-4092-4972-bf72-042d5392cbbd.png">

We already have added the link to the next event.

**Comment by Yago** [comment]
Ok, so I will add the YouTube button, even if we have a subscribe button on the event.

**Comment by WengerK** [comment]
Thx for your reactivity :)

**Comment by Yago** [comment]
Done and [released](https://github.com/webmardi/webmardi.ch/releases/tag/v1.1.6) !

**Comment by WengerK** [comment]
thx 🥇
