### ISSUE TITLE
Add an icon for mastodon

### ISSUE THREAD

**Issue by Greaby** [webmardi/webmardi.ch#78]
We recently created a Mastodon account. 
@Yago Could you add an icon for the mastodon in the header?

Here is the link : https://tooting.ch/@webmardi

**Comment by Yago** [comment]
Sure, good initiative ! I'll do it Friday 😉

**Comment by Yago** [comment]
Done and [released](https://github.com/webmardi/webmardi.ch/releases/tag/v1.1.6) !

**Comment by WengerK** [comment]
thx 🥇
