### ISSUE TITLE
Mettre en place G4

### ISSUE THREAD

**Issue by WengerK** [webmardi/webmardi.ch#86]
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-4PZVCNZ6D5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-4PZVCNZ6D5');
</script>
```

**Comment by WengerK** [comment]
Il semblerait que le code est déjà présent mais pas dans le composant SEO. Est-ce normal ?

**Comment by Yago** [comment]
Il semble qui soit ajouté via GTM 🤔

<img width="913" alt="CleanShot 2023-05-12 at 09 44 55@2x" src="https://github.com/webmardi/webmardi.ch/assets/2025924/ab3d4a73-19f3-482e-9bcb-db283009fa43">

**Comment by WengerK** [comment]
Ohhh !! Perfect then ! Same for the old Google-Analytics, also added via GTM ?

**Comment by Yago** [comment]
No manually, I just release with GA4 properly integrated, you can remove GTM integration 😉 → https://github.com/webmardi/webmardi.ch/releases/tag/v1.2.3

If you want me to remove GA3, just tell me.

**Comment by WengerK** [comment]
well if both works together lets keep them all, I will ask Sacha how we should proceed to finalize GA4 and then remove GA3
