### ISSUE TITLE
https://webmardi.ch/events/ gives a 403

### ISSUE THREAD

**Issue by gperriard** [webmardi/webmardi.ch#87]
How to reproduce
When I browse https://webmardi.ch/events
Then I redirected to https://webmardi.ch/events/
And I get a 403
![Screenshot 2023-07-19 at 17 12 31](https://github.com/webmardi/webmardi.ch/assets/1012526/95394eee-4f17-4056-87ce-140b7abf4f82)

**Comment by Yago** [comment]
Ticket ouvert chez Infomaniak

**Comment by Yago** [comment]
Fixed with https://github.com/webmardi/webmardi.ch/releases/tag/v1.4.0
