### ISSUE TITLE
Redirection from http to https

### ISSUE THREAD

**Issue by gperriard** [webmardi/webmardi.ch#95]
<img width="839" alt="Capture" src="https://github.com/webmardi/webmardi.ch/assets/1012526/c6b697e0-86d9-4d16-a579-5ba32c39df58">

It seems that the automatic redirection from http://webmardi.ch to https://webmardi.ch is broken. Could you please have a look at it? Thx :)

**Comment by Yago** [comment]
I just take a look and it seems working again... Can you confirm it @gperriard ?

(Sorry for the delay, feel free to assign any issue to me, otherwise I won't be notified.)
